publish:
- provider: generic
  url: 
appId: 
productName: 
asar: false
win:
  publisherName: 
  rfc3161TimeStampServer: http://sha256timestamp.ws.symantec.com/sha256/timestamp
  timeStampServer: http://timestamp.globalsign.com/scripts/timstamp.dll
linux:
  category: Education
files:
- "node_modules/**"
- "build/**"
- "src/**"
- "!src/app"
directories:
  output: dist-dev